const listData = [
  {
    memberQuizId: 1,
    submissionAnswer: '인덱싱이란?..',
    solvedDateTime: '2023-11-02 12:00:00',
    feedback: '설명이 부족합니다...',
    point: '문장유사도 기반 점수',
    OblivionStatus: 'OBLIVION_STATUS_1',
    quizId: 1,
    quizContent: '데이터베이스에서 인덱싱이란 무엇인가요?',
    quizAnswer: '인덱싱이란..',
    tag: 'DATA_BASE',
  },
  {
    memberQuizId: 2,
    submissionAnswer: '인덱싱이란?..',
    feedback: '설명이 부족합니다...',
    point: '문장유사도 기반 점수',
    solvedDateTime: '2023-11-02 12:00:00',
    OblivionStatus: 'OBLIVION_STATUS_1',
    quizId: 1,
    quizContent: '데이터베이스에서 인덱싱이란 무엇인가요?',
    quizAnswer: '인덱싱이란..',
    tag: 'DATA_BASE',
  },
  {
    memberQuizId: 3,
    submissionAnswer: '인덱싱이란?..',
    feedback: '설명이 부족합니다...',
    point: '문장유사도 기반 점수',
    solvedDateTime: '2023-11-02 12:00:00',
    OblivionStatus: 'OBLIVION_STATUS_1',
    quizId: 1,
    quizContent: '데이터베이스에서 인덱싱이란 무엇인가요?',
    quizAnswer: '인덱싱이란..',
    tag: 'DATA_BASE',
  },
  {
    memberQuizId: 4,
    submissionAnswer: '인덱싱이란?..',
    feedback: '설명이 부족합니다...',
    point: '문장유사도 기반 점수',
    solvedDateTime: '2023-11-02 12:00:00',
    OblivionStatus: 'OBLIVION_STATUS_1',
    quizId: 1,
    quizContent: '데이터베이스에서 인덱싱이란 무엇인가요?',
    quizAnswer: '인덱싱이란..',
    tag: 'DATA_BASE',
  },
  // {
  //   memberQuizId: 5,
  //   submissionAnswer: '인덱싱이란?..',
  //   feedback: '설명이 부족합니다...',
  //   point: '문장유사도 기반 점수',
  //   solvedDateTime: '2023-11-02 12:00:00',
  //   OblivionStatus: 'OBLIVION_STATUS_1',
  //   quizId: 1,
  //   quizContent: '데이터베이스에서 인덱싱이란 무엇인가요?',
  //   quizAnswer: '인덱싱이란..',
  //   tag: 'DATA_BASE',
  // },
  // {
  //   memberQuizId: 6,
  //   submissionAnswer: '인덱싱이란?..',
  //   feedback: '설명이 부족합니다...',
  //   point: '문장유사도 기반 점수',
  //   solvedDateTime: '2023-11-02 12:00:00',
  //   OblivionStatus: 'OBLIVION_STATUS_1',
  //   quizId: 1,
  //   quizContent: '데이터베이스에서 인덱싱이란 무엇인가요?',
  //   quizAnswer: '인덱싱이란..',
  //   tag: 'DATA_BASE',
  // },
  // {
  //   memberQuizId: 7,
  //   submissionAnswer: '인덱싱이란?..',
  //   feedback: '설명이 부족합니다...',
  //   point: '문장유사도 기반 점수',
  //   solvedDateTime: '2023-11-02 12:00:00',
  //   OblivionStatus: 'OBLIVION_STATUS_1',
  //   quizId: 1,
  //   quizContent: '데이터베이스에서 인덱싱이란 무엇인가요?',
  //   quizAnswer: '인덱싱이란..',
  //   tag: 'DATA_BASE',
  // },
  // {
  //   memberQuizId: 8,
  //   submissionAnswer: '인덱싱이란?..',
  //   feedback: '설명이 부족합니다...',
  //   point: '문장유사도 기반 점수',
  //   solvedDateTime: '2023-11-02 12:00:00',
  //   OblivionStatus: 'OBLIVION_STATUS_1',
  //   quizId: 1,
  //   quizContent: '데이터베이스에서 인덱싱이란 무엇인가요?',
  //   quizAnswer: '인덱싱이란..',
  //   tag: 'DATA_BASE',
  // },
  // {
  //   memberQuizId: 9,
  //   submissionAnswer: '인덱싱이란?..',
  //   feedback: '설명이 부족합니다...',
  //   point: '문장유사도 기반 점수',
  //   solvedDateTime: '2023-11-02 12:00:00',
  //   OblivionStatus: 'OBLIVION_STATUS_1',
  //   quizId: 1,
  //   quizContent: '데이터베이스에서 인덱싱이란 무엇인가요?',
  //   quizAnswer: '인덱싱이란..',
  //   tag: 'DATA_BASE',
  // },
];

export { listData };
