const listData = [
  {
    id: 1,
    title: '데이터베이스의 특징',
    numberSolved: 12345,
    averageScore: 67,
    tag: ['데이터베이스'],
  },
  {
    id: 2,
    title: '데이터베이스 언어 DDL, DML, DCL에 대해 설명',
    numberSolved: 54321,
    averageScore: 12,
    tag: ['데이터베이스'],
  },
  {
    id: 3,
    title: '트리거에 대해 설명',
    numberSolved: 98765,
    averageScore: 34,
    tag: ['데이터베이스'],
  },
  {
    id: 4,
    title: 'Index의 정의와 장단점을 설명',
    numberSolved: 24680,
    averageScore: 56,
    tag: ['데이터베이스'],
  },
  {
    id: 5,
    title: '정규화에 대해 설명',
    numberSolved: 13579,
    averageScore: 78,
    tag: ['데이터베이스'],
  },
  {
    id: 6,
    title: '정규화의 장단점을 설명',
    numberSolved: 80246,
    averageScore: 45,
    tag: ['데이터베이스'],
  },
  {
    id: 7,
    title: '역정규화를 하는 이유',
    numberSolved: 64280,
    averageScore: 32,
    tag: ['데이터베이스'],
  },
  {
    id: 8,
    title: '이상 현상의 종류와 정의',
    numberSolved: 56789,
    averageScore: 90,
    tag: ['데이터베이스'],
  },
  {
    id: 9,
    title: 'SQL INJECTION이 무엇인지 설명',
    numberSolved: 13579,
    averageScore: 87,
    tag: ['데이터베이스'],
  },
  {
    id: 10,
    title: 'SQL INJECTION을 방어 및 방지하는 방법',
    numberSolved: 98765,
    averageScore: 23,
    tag: ['데이터베이스'],
  },
  {
    id: 11,
    title: 'RDBMS와 NoSQL의 차이',
    numberSolved: 24680,
    averageScore: 54,
    tag: ['데이터베이스'],
  },
  {
    id: 12,
    title: 'RDBMS와 NoSQL은 어느 경우에 적합한가요',
    numberSolved: 80246,
    averageScore: 76,
    tag: ['데이터베이스'],
  },
  {
    id: 13,
    title: '트랜잭션이란 무엇인지 설명',
    numberSolved: 64280,
    averageScore: 21,
    tag: ['데이터베이스'],
  },
  {
    id: 14,
    title: '트랜잭션의 특성에 대해 설명',
    numberSolved: 56789,
    averageScore: 89,
    tag: ['데이터베이스'],
  },
  {
    id: 15,
    title: '데이터베이스 락에 대해 설명',
    numberSolved: 13579,
    averageScore: 34,
    tag: ['데이터베이스'],
  },
  {
    id: 16,
    title: 'Elastic Search의 키워드 검색과 RDBMS의 LIKE 검색의 차이',
    numberSolved: 98765,
    averageScore: 56,
    tag: ['데이터베이스'],
  },
  {
    id: 17,
    title: '옵티마이저에 대해 설명',
    numberSolved: 24680,
    averageScore: 78,
    tag: ['데이터베이스'],
  },
  {
    id: 18,
    title: 'inner join과 outer join의 차이',
    numberSolved: 80246,
    averageScore: 90,
    tag: ['데이터베이스'],
  },
  {
    id: 19,
    title: 'group by의 역할에 대해 설명',
    numberSolved: 64280,
    averageScore: 32,
    tag: ['데이터베이스'],
  },
  {
    id: 20,
    title: 'DELETE, TRUNCATE, DROP의 차이',
    numberSolved: 56789,
    averageScore: 87,
    tag: ['데이터베이스'],
  },
  {
    id: 21,
    title: 'JOIN에서 ON과 WHERE의 차이',
    numberSolved: 13579,
    averageScore: 23,
    tag: ['데이터베이스'],
  },
];

export { listData };
