spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/devgenie
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
    defer-datasource-initialization: true

  data:
    web:
      pageable:
        one-indexed-parameters: true
#        default-page-size: 5
#        max-page-size: 2000
  sql:
    init:
      data-locations: classpath*:db/data.sql
      mode: always
      platform: h2

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace